dist: trusty
addons:
  chrome: stable
  browserstack:
    forcelocal: true
    username: "$BROWSERSTACK_USERNAME"
    access_key: "$BROWSERSTACK_ACCESS_KEY"
language: node_js
node_js:
- "8"
before_install:
- echo "TRAVIS_BRANCH:" + "$TRAVIS_BRANCH"
- echo "TRAVIS_PULL_REQUEST:" + "$TRAVIS_PULL_REQUEST"
- echo "TRAVIS_PULL_REQUEST_BRANCH:" + "$TRAVIS_PULL_REQUEST_BRANCH"
- echo "TRAVIS_TAG:" + "$TRAVIS_TAG"
- nvm install 8
- npm i -g firebase-tools@6.3.1 @angular/cli@7.3.0 selenium-webdriver @commitlint/travis-cli
install:
- npm i -g ncp del-cli @compodoc/compodoc
- npm install
- cd functions && npm install && cd ..
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
- ng -v
script:
- commitlint-travis
- npm run lint
- npm run test:cover
- npm run e2e:browserstack
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage -p . --token "$CODACY_PROJECT_TOKEN"
- if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then firebase deploy --project supermurat-com --token "$FIREBASE_TOKEN" -m "Deploying by Travis CI - Build $TRAVIS_BUILD_NUMBER# $TRAVIS_BUILD_WEB_URL" --non-interactive; fi
after_success:
- echo "!after_success!"
after_failure:
- echo "!after_failure!"
after_script:
- echo "!after_script!"
